"""Added user table

Revision ID: a02f24daf4a9
Revises: 2101d2e4b3a7
Create Date: 2024-01-02 08:22:34.385073

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02f24daf4a9'
down_revision: Union[str, None] = '2101d2e4b3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mobile_no')
    # ### end Alembic commands ###
